### ISSUE TITLE
[PluginName] Issue: As of today, tabs channels are not changing anymore, and if I reinstall the plugin, it doesn't work at all

### ISSUE THREAD

**Issue by arkduquez** [samfundev/BetterDiscordStuff#11]
As of today, tabs channels are not changing anymore, and if I reinstall the plugin, it doesn't work at all, all of my friends are having similar issues, any fix for this?

**Comment by flamedance58** [comment]
Can confirm this.
I don't have any other plugins that effect tabs, haven't altered the code at all, and for some reason the tabs won't change to the name of the channel their now in.

**Comment by wstirl** [comment]
can confirm it doesn't work anymore

**Comment by MegaShinySnivy** [comment]
Also can confirm. Not noticing anything interesting or relevant in the logs though.

**Comment by nirgranth** [comment]
https://github.com/samfundev/BetterDiscordStuff/pull/14
