### ISSUE TITLE
[PluginName] Issue: just not working or showing up at all

### ISSUE THREAD

**Issue by suddenlysocks** [samfundev/BetterDiscordStuff#15]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
i've downloaded channel tabs, it's not showing up as if it's not even there. the file name is correct and everything, i've tried uninstalling and reinstalling, nothing.

**To Reproduce**
1. Go to your plugins
2. Click on the option to turn on channel tabs
3. nothing happens

**Expected behavior**
to have channeltabs

**Screenshots**
Please also check the console by pressing `Ctrl + Shift + I` and send screenshots of errors (red messages)

**Information (please complete the following information):**
 - OS: MacOS
 - Plugin Version: 3
 - Discord version: [PTB, Stable, Canary]
 - Compact Mode enabled? no

**Additional context**

**Comment by nirgranth** [comment]
https://github.com/samfundev/BetterDiscordStuff/pull/14

**Comment by samfundev** [comment]
Please check out https://github.com/samfundev/BetterDiscordStuff/issues/5, if the new version doesn't work for you please open a issue.
