### ISSUE TITLE
[ChannelTabs] doesn't work

### ISSUE THREAD

**Issue by fowlis** [samfundev/BetterDiscordStuff#5]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
I hate to say "it doesn't work", but I can't describe the issue any other way.
The bar doesn't show with the tabs, the plugin gives errors both as soon as it starts, and when you switch DMs/channels

**To Reproduce**
1. Enable plugin
2. Plugin doesn't do anything
3. Success

**Screenshots**
Error given as soon as you enable the plugin:
![DiscordPTB_yvbedTvXy5](https://github.com/user-attachments/assets/b9cd4d6f-d64e-4205-bb7c-e12e78a33e50)
(seems like it fails to create the config file)

Another error when switching DMs/channels:
![DiscordPTB_Ilg1rMEDa6](https://github.com/user-attachments/assets/448b4ba1-f68a-4489-90a1-ccf29d235a6b)

**Information (please complete the following information):**
 - OS: Windows 10
 - Plugin Version: 2.6.13
 - Discord version: only tested on my PTB client
 - Compact Mode enabled? no

**Additional context**
Two other people in the BD support server are having this issue, but neither gave the info I have included in this post.

**Comment by bogo09** [comment]
Mine doesn't show any error, just doesn't work.

**Comment by Anchoasalta** [comment]
After reading the post I noticed the comment you made about the plugin trying to create a configuration file, and I realized that the only thing to do is to rename the normal configuration file to the name that the console tells you.

**Comment by DimTheEnderman** [comment]
One of my buds is having the same exact problem

**Comment by fowlis** [comment]
> After reading the post I noticed the comment you made about the plugin trying to create a configuration file, and I realized that the only thing to do is to rename the normal configuration file to the name that the console tells you.

While I'm not sure this fixes the other error, it probably fixes the plugin's functionality - at least temporarily.
Here's the how-to:
1. Find your user ID - enable Dev Tools in Discord, right click your username anywhere on Discord -> "Copy User ID"
(Or open the console and read the error message ChannelTabs gives about "ENOENT: no such file or directory", you'll see your user ID there)
2. Go to your BetterDiscord plugins folder.
3. Create a new Text file, rename it to `ChannelTabs_new_<UserID>.config.json` where UserID is, obviously, your User ID from earlier.
For example, for me it would be `ChannelTabs_new_234600632567201792.config.json`
4. Success! You may need to reload/restart Discord for it to work again.

Again, this is a *temporary* solution, if the plugin stops working again after doing this fix, then it likely needs a proper fix from the dev.

**Comment by fireshaper** [comment]
I get the same error on a new install of the plugin with BetterDiscord on Fedora Linux. It didn't create the user-specific config.json file. I just copied the file name from the error and manually created the file in the plugins folder. Restarting Discord was necessary.

**Comment by piemantr** [comment]
> > After reading the post I noticed the comment you made about the plugin trying to create a configuration file, and I realized that the only thing to do is to rename the normal configuration file to the name that the console tells you.
> 
> While I'm not sure this fixes the other error, it probably fixes the plugin's functionality - at least temporarily. Here's the how-to:
> 
> 1. Find your user ID - enable Dev Tools in Discord, right click your username anywhere on Discord -> "Copy User ID"
>    (Or open the console and read the error message ChannelTabs gives about "ENOENT: no such file or directory", you'll see your user ID there)
> 2. Go to your BetterDiscord plugins folder.
> 3. Create a new Text file, rename it to `ChannelTabs_new_<UserID>.config.json` where UserID is, obviously, your User ID from earlier.
>    For example, for me it would be `ChannelTabs_new_234600632567201792.config.json`
> 4. Success! You may need to reload/restart Discord for it to work again.
> 
> Again, this is a _temporary_ solution, if the plugin stops working again after doing this fix, then it likely needs a proper fix from the dev.

Yep, this allows me to use my bookmarks but now the tabs are stuck on Friends so opening multiple tabs have no use. Dev needs to fix.

**Comment by nirgranth** [comment]
https://github.com/samfundev/BetterDiscordStuff/pull/14

**Comment by nirgranth** [comment]
> Yep, this allows me to use my bookmarks but now the tabs are stuck on Friends so opening multiple tabs have no use. Dev needs to fix.

Check the pull it still has image not error as it depends on zeres plugin lib but rest show work

**Comment by samfundev** [comment]
The fix for this has been released in v2.6.14. It has not been approved yet, but feel free to [download the latest version](https://raw.githubusercontent.com/samfundev/BetterDiscordStuff/refs/heads/master/Plugins/ChannelTabs/ChannelTabs.plugin.js) in the mean time.

**Comment by samfundev** [comment]
v2.6.14 has been approved, so I'm going to close this.
