### ISSUE TITLE
[ChannelTabs] Issue: ChannelTabs could not be started

### ISSUE THREAD

**Issue by JayRPlayz** [samfundev/BetterDiscordStuff#9]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
i got banned from a discord server and now channelTabs is failing to start

**To Reproduce**
1. Enable ChannelTabs
2. create a new tab
3. in that new tab go to a discord server
4. get kicked or banned from there while having a different tab active
5. restart betterdiscord
6. watch how the plugin failes to start

**Screenshots**
![image](https://github.com/user-attachments/assets/b192bcfe-b842-4c38-a5d0-52404afc5dd8)

**Information:**

 - OS: Windows 11
 - Plugin Version: 2.6.13
 - Discord version: Stable

**Comment by marmoris-x** [comment]
The same applies to me. Please fix it. This is a life-saving plugin.

**Comment by wstirl** [comment]
can confirm it doesn't work anymore

**Comment by samfundev** [comment]
I may be wrong, but this might be related to #5. Please check out the new version and if this issue hasn't been fixed feel free to reopen this issue.
